<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SeriesRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class SeriesRepository extends EntityRepository {

    public function  getSeries () {
        return $this->createQueryBuilder('s')
           ->getQuery()->getResult();
    }

}
